#!/bin/bash -l

# Project name
#$ -P sv-thesis

#Time limit
#$ -l h_rt=24:00:00

#Name a job
#$ -N Simulation

#join error and output stream
#$ -j y

#Send email when job ends or aborts
#$-m e

#Name the log file
##$-o SimLog

#This line runs the set of nSim simulations this many times
#$-t 1-20

#Other options that were in script from JB
#$-l mem_per_core=8G
#$-pe omp 8
#$-l cpu_arch=!bulldozer

#Arguments are:
	#sample size
	#reproductive number
	#generation interval shape
	#generation interval scale
	#mutation rate
	#lower SNP threshold (link)
	#upper SNP threshold (nonlink)
	#initial shape parameter
	#initial scale parameter
module load R/3.6.0
time Rscript PerformSimulationSIFull.R $1 $2 $3 $4 $5 $6 $7 $8 $9
